
language: generic

# Explicitly request container-based infrastructure.
sudo: false

matrix:
  allow_failures:
     - env: GHC=head EVM_EMACS=emacs-24.4-travis
     - env: GHC=head EVM_EMACS=emacs-25.3-travis

  include:
    - env: GHC=7.2.2 EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC 7.2.2, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.2.2], sources: [hvr-ghc]}}

    - env: GHC=7.4.2 EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC 7.4.2, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.4.2], sources: [hvr-ghc]}}

    - env: GHC=7.6.3 EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC 7.6.3, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.6.3], sources: [hvr-ghc]}}

    - env: GHC=7.8.4 EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC 7.8.4, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}

    - env: GHC=7.10.3 EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC 7.10.3, EMACS 25.3"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

    - env: GHC=8.0.2 EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC 8.0.2, EMACS 25.3"
      addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}

    - env: GHC=8.2.2 EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC 8.2.2, EMACS 25.3"
      addons: {apt: {packages: [ghc-8.2.2], sources: [hvr-ghc]}}

    - env: GHC=8.4.1 EVM_EMACS=emacs-24.4-travis
      compiler: ": GHC 8.4.1, EMACS 24.4"
      addons: {apt: {packages: [ghc-8.4.1], sources: [hvr-ghc]}}

    - env: GHC=8.4.1 EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC 8.4.1, EMACS 25.3"
      addons: {apt: {packages: [ghc-8.4.1], sources: [hvr-ghc]}}

    - env: GHC=head EVM_EMACS=emacs-25.3-travis
      compiler: ": GHC HEAD, EMACS 25.3"
      addons: {apt: {packages: [ghc-head], sources: [hvr-ghc]}}

install: true

before_install:

  # Using compiler above sets CC to an invalid value, so unset it
  - unset CC

  - export PATH="/opt/ghc/$GHCVER/bin:$PATH"

   # ????
  - mkdir -p ~/.local/bin

  - |
    if [ -n "$EVM_EMACS" ]; then
      git clone https://github.com/rejeep/evm.git $HOME/.evm
      export PATH="$HOME/.evm/bin:$PATH"
      evm config path /tmp
      evm install "$EVM_EMACS" --use --skip
      # Use cask to install elisp dependencies
      git clone https://github.com/cask/cask.git "$HOME/.cask"
      export PATH="$HOME/.cask/bin:$PATH"
    fi

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - echo "$(ghc-pkg list)"

script:
  - make compile
  # FIXME: Restore hlint as soon as we find a simple way to install it on Travis CI
  # - make HLINTFLAGS=-c lint
  - make test
